### ISSUE TITLE
Missing CRS for HPC locations

### ISSUE THREAD

**Issue by khelfen** [rl-institut/tracbev#25]
When running the standard potential scenario with `python -m tracbev potential_scenario --mode potential` the CRS for the HPC output is missing. I did not check it for other scenarios.

![image](https://user-images.githubusercontent.com/46815982/180161849-3210f436-70d3-467f-9a0b-0a20475661d1.png)

**Comment by mosc5** [comment]
This issue seems to stem from the input file hpc_positions.gpkg having an undefined crs. This could be hotfixed via the set_crs function, but that would not lead to consistent behaviour with custom input data. As a solution I propose fixing the input data set and using that opportunity to update the input data with the newest information for existing charging infrastructure. As such I will close this Issue and instead work on it in Issue #29
